import { Button, Card, CardBody, CardFooter, CardHeader } from 'grommet';
import { Add } from 'grommet-icons';
import moment from 'moment';
import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { data } from '../store';
import styles from '../styles/Home.module.css';

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
          My Dates
        </h2>

        <div className={styles.grid}>
          {data.map(d => <Card key={d.id} background="light-1">
            <CardHeader pad="medium">
              {d.name}
            </CardHeader>
            <CardBody pad="medium">
              <div>{d.dates.length} {d.dates.length === 1 ? "date" : "dates"}</div>
              <div>{moment(d.dates[0].date).format("MMMM DD")}</div>
            </CardBody>
          </Card>)}

          <Card background="light-1">
            <CardHeader pad="medium">
              Someone new
            </CardHeader>
            <CardFooter background="light-2">
              <Button hoverIndicator icon={<Add />} onClick={() => router.push("/person/new/1")} />
            </CardFooter>
          </Card>
        </div>
      </main>

    </div>
  )
}
